"""Dataset access.

Two sources, one interface:

* ``load_dataset(source="real")``  -- the genuine UCI Maternal Health Risk Data
  Set (id 863). Read from ``data/raw/`` if present; ``scripts/download_data.py``
  fetches it.
* ``load_dataset(source="bundled")`` -- a deterministic **synthetic** stand-in
  generated by this module so the whole pipeline runs on a clean checkout with
  no network. It is not real patient data, and every artifact produced from it
  is stamped as such.

``load_dataset("auto")`` prefers the real file and falls back to the synthetic
one, reporting which it used. Nothing here silently substitutes synthetic data
for real data.
"""
from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd

from . import config as C

# ---------------------------------------------------------------------------
# Reference marginals
# ---------------------------------------------------------------------------
# Descriptive statistics of the real UCI file, transcribed from its published
# summary so the synthetic stand-in lands in the same numeric neighbourhood.
# These are an *approximation of published summaries*, not a copy of the data --
# verify them against the real file before quoting any of them in a write-up.
REFERENCE_MARGINALS = {
    "n_rows": 1014,
    "class_counts": {"low risk": 406, "mid risk": 336, "high risk": 272},
    "ranges": {
        "Age": (10, 70),
        "SystolicBP": (70, 160),
        "DiastolicBP": (49, 100),
        "BS": (6.0, 19.0),
        "BodyTemp": (98.0, 103.0),
        "HeartRate": (7, 90),
    },
}

# Class-conditional centres for the generator. Chosen so the guideline
# thresholds in ``guidelines.py`` are *partially* -- not perfectly -- aligned
# with the labels, which is the situation the calibration study exists to
# measure. Perfect agreement would make that analysis vacuous.
_CLASS_PROFILE = {
    "low risk": {"Age": (24, 6), "SystolicBP": (109, 10), "DiastolicBP": (72, 8),
                 "BS": (7.0, 0.9), "BodyTemp": (98.3, 0.5), "HeartRate": (72, 7)},
    "mid risk": {"Age": (29, 9), "SystolicBP": (121, 13), "DiastolicBP": (79, 9),
                 "BS": (8.6, 2.2), "BodyTemp": (98.7, 1.0), "HeartRate": (76, 8)},
    "high risk": {"Age": (34, 11), "SystolicBP": (133, 15), "DiastolicBP": (88, 9),
                  "BS": (13.2, 3.4), "BodyTemp": (99.4, 1.5), "HeartRate": (79, 9)},
}

# Body temperature in the real file is nurse-recorded in Fahrenheit and lands on
# a small set of values rather than a continuum. Reproducing that quantisation
# matters: otherwise a model can exploit spurious decimal precision.
# Weighted toward 98.0F, which dominates the real file (mean approx. 98.7F);
# an unweighted grid would put the synthetic mean a full degree too high.
_TEMP_GRID = np.array([98.0, 98.6, 99.0, 100.0, 101.0, 102.0, 103.0])
# Per-class weights: fever is uncommon overall but concentrated in the
# higher-risk classes, so the grid has to be class-conditional rather than a
# single shared distribution with class-varying jitter.
_TEMP_WEIGHTS = {
    "low risk":  np.array([0.82, 0.10, 0.04, 0.02, 0.01, 0.005, 0.005]),
    "mid risk":  np.array([0.70, 0.11, 0.05, 0.07, 0.04, 0.02, 0.01]),
    "high risk": np.array([0.55, 0.11, 0.06, 0.11, 0.08, 0.05, 0.04]),
}


@dataclass(frozen=True)
class DatasetInfo:
    """Provenance for whatever ``load_dataset`` handed back."""

    source: str            # "real" | "bundled-synthetic"
    is_synthetic: bool
    path: Path
    n_rows: int
    sha256: str
    note: str

    def banner(self) -> str:
        if self.is_synthetic:
            return (
                "SYNTHETIC DATA -- results are a pipeline demonstration only and "
                "carry no clinical meaning. Re-run on the real UCI dataset before "
                "citing any number."
            )
        return f"Real dataset: {self.path.name} ({self.n_rows} rows, sha256={self.sha256[:12]})"


# ---------------------------------------------------------------------------
# Synthetic generator
# ---------------------------------------------------------------------------
def generate_synthetic(n_rows: int | None = None, seed: int = C.RANDOM_SEED) -> pd.DataFrame:
    """Build the deterministic synthetic stand-in.

    Deliberately reproduces three awkward properties of the real file, because a
    pipeline that only works on clean data is not a useful pipeline:

    1. implausible ``HeartRate`` values (the real file contains 7 bpm entries);
    2. exact duplicate rows;
    3. label noise, so the classes are not separable and accuracy lands in the
       same band as the published literature rather than at a suspicious 99%.
    """
    rng = np.random.default_rng(seed)
    n_rows = n_rows or REFERENCE_MARGINALS["n_rows"]

    counts = REFERENCE_MARGINALS["class_counts"]
    total = sum(counts.values())
    per_class = {k: int(round(v / total * n_rows)) for k, v in counts.items()}
    # Absorb any rounding drift into the majority class.
    per_class["low risk"] += n_rows - sum(per_class.values())

    frames = []
    for label, n in per_class.items():
        prof = _CLASS_PROFILE[label]
        jitter = rng.normal(0, 0.15, n) if prof["BodyTemp"][1] > 0.8 else 0.0
        block = pd.DataFrame({
            "Age": rng.normal(*prof["Age"], n),
            "SystolicBP": rng.normal(*prof["SystolicBP"], n),
            "DiastolicBP": rng.normal(*prof["DiastolicBP"], n),
            "BS": rng.normal(*prof["BS"], n),
            "BodyTemp": rng.choice(_TEMP_GRID, n, p=_TEMP_WEIGHTS[label]) + jitter,
            "HeartRate": rng.normal(*prof["HeartRate"], n),
        })
        block[C.TARGET] = label
        frames.append(block)

    df = pd.concat(frames, ignore_index=True)

    # Clip to the published ranges, then discretise the way a clinic form would.
    for col, (lo, hi) in REFERENCE_MARGINALS["ranges"].items():
        df[col] = df[col].clip(lo, hi)
    for col in ("Age", "SystolicBP", "DiastolicBP", "HeartRate"):
        df[col] = df[col].round().astype(int)
    df["BS"] = df["BS"].round(1)
    df["BodyTemp"] = df["BodyTemp"].round(1)

    # (1) Implausible heart rates, as in the real file.
    bad_hr = rng.choice(df.index, size=2, replace=False)
    df.loc[bad_hr, "HeartRate"] = 7

    # (3) Label noise concentrated on the mid/high boundary -- the boundary
    # clinicians themselves disagree about, and the reason ordinal-aware
    # metrics matter more here than plain accuracy.
    flip = rng.choice(df.index, size=int(0.07 * len(df)), replace=False)
    neighbour = {"low risk": "mid risk", "mid risk": "high risk", "high risk": "mid risk"}
    df.loc[flip, C.TARGET] = df.loc[flip, C.TARGET].map(neighbour)

    df = df.sample(frac=1.0, random_state=seed).reset_index(drop=True)

    # (2) Exact duplicates. Make room for them first, otherwise trimming back to
    # n_rows would discard the very rows being injected.
    n_dupes = 12
    keep = df.head(n_rows - n_dupes)
    dupes = keep.sample(n=n_dupes, random_state=seed + 1)
    df = (
        pd.concat([keep, dupes], ignore_index=True)
        .sample(frac=1.0, random_state=seed + 2)
        .reset_index(drop=True)
    )

    return df[C.FEATURES + [C.TARGET]]


def write_bundled(path: Path | None = None) -> Path:
    """Materialise the synthetic CSV under ``data/bundled/``."""
    path = path or C.BUNDLED_CSV
    path.parent.mkdir(parents=True, exist_ok=True)
    generate_synthetic().to_csv(path, index=False)
    return path


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------
def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _find_real_csv() -> Path | None:
    if C.RAW_CSV.exists():
        return C.RAW_CSV
    hits = sorted(C.RAW_DIR.glob("*.csv"))
    return hits[0] if hits else None


def load_dataset(source: str = "auto") -> tuple[pd.DataFrame, DatasetInfo]:
    """Return ``(dataframe, provenance)``.

    ``source`` is ``"auto"`` (real if available, else synthetic), ``"real"``
    (raise if missing), or ``"bundled"`` (always synthetic).
    """
    if source not in {"auto", "real", "bundled"}:
        raise ValueError(f"source must be auto|real|bundled, got {source!r}")

    real = _find_real_csv() if source in {"auto", "real"} else None

    if source == "real" and real is None:
        raise FileNotFoundError(
            f"No real dataset in {C.RAW_DIR}. Run: python scripts/download_data.py"
        )

    if real is not None:
        df = pd.read_csv(real)
        missing = [c for c in C.FEATURES + [C.TARGET] if c not in df.columns]
        if missing:
            raise ValueError(f"{real.name} is missing expected columns: {missing}")
        info = DatasetInfo("real", False, real, len(df), _sha256(real),
                           "Genuine UCI Maternal Health Risk Data Set.")
        return df[C.FEATURES + [C.TARGET]].copy(), info

    if not C.BUNDLED_CSV.exists():
        write_bundled()
    df = pd.read_csv(C.BUNDLED_CSV)
    info = DatasetInfo(
        "bundled-synthetic", True, C.BUNDLED_CSV, len(df), _sha256(C.BUNDLED_CSV),
        "Deterministic synthetic stand-in from mhrisk.data.generate_synthetic.",
    )
    return df, info


# ---------------------------------------------------------------------------
# Cleaning
# ---------------------------------------------------------------------------
# Physiologically possible bounds. Anything outside these is a recording error,
# not an extreme patient -- a resting heart rate of 7 bpm is a typo. Repairing
# rather than dropping keeps the row's other five usable vitals in play.
PLAUSIBLE = {
    "Age": (10, 60),
    "SystolicBP": (70, 200),
    "DiastolicBP": (40, 130),
    "BS": (3.0, 30.0),
    "BodyTemp": (95.0, 106.0),
    "HeartRate": (40, 180),
}


@dataclass
class CleaningReport:
    n_in: int
    n_out: int
    duplicates_dropped: int
    implausible_by_column: dict[str, int]
    label_counts: dict[str, int]

    def summary(self) -> str:
        flagged = {k: v for k, v in self.implausible_by_column.items() if v}
        return (
            f"{self.n_in} rows in -> {self.n_out} out; "
            f"{self.duplicates_dropped} duplicates dropped; "
            f"implausible values repaired: {flagged or 'none'}"
        )


def clean(df: pd.DataFrame) -> tuple[pd.DataFrame, CleaningReport]:
    """Normalise labels, drop duplicates, repair implausible vitals."""
    n_in = len(df)
    out = df.copy()

    out[C.TARGET] = (
        out[C.TARGET].astype(str).str.strip().str.lower()
        .str.replace(r"\s+", " ", regex=True)
    )
    unknown = set(out[C.TARGET]) - set(C.LABELS)
    if unknown:
        raise ValueError(f"Unrecognised risk labels: {sorted(unknown)}")

    before = len(out)
    out = out.drop_duplicates().reset_index(drop=True)
    duplicates_dropped = before - len(out)

    # Median-impute implausible readings, computed per risk class so a repaired
    # value is at least consistent with the rest of that class.
    implausible: dict[str, int] = {}
    for col, (lo, hi) in PLAUSIBLE.items():
        mask = (out[col] < lo) | (out[col] > hi)
        implausible[col] = int(mask.sum())
        if mask.any():
            out.loc[mask, col] = np.nan
            out[col] = out.groupby(C.TARGET)[col].transform(lambda s: s.fillna(s.median()))

    report = CleaningReport(
        n_in=n_in,
        n_out=len(out),
        duplicates_dropped=duplicates_dropped,
        implausible_by_column=implausible,
        label_counts=out[C.TARGET].value_counts().reindex(C.LABELS).to_dict(),
    )
    return out, report


def split_xy(df: pd.DataFrame) -> tuple[pd.DataFrame, np.ndarray]:
    """Features frame and integer-encoded ordinal target."""
    y = df[C.TARGET].map(C.LABEL_TO_INT).to_numpy()
    return df[C.FEATURES].copy(), y
