"""Regenerate the paper's tables from ``artifacts/``.

    python scripts/make_paper_tables.py

Writes ``paper/generated_tables.md``. The point is that no number in the paper is
typed by hand: after any re-run (especially the switch from synthetic to real
data) this regenerates every table, and a stale figure in the prose becomes
visible instead of surviving unnoticed.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

import _bootstrap  # noqa: F401

from mhrisk import config as C

HEADLINE = ["high_risk_recall", "critical_miss_rate", "expected_cost",
            "referral_rate", "balanced_accuracy", "accuracy"]

PRETTY = {
    "high_risk_recall": "High-risk recall",
    "critical_miss_rate": "Critical miss rate",
    "expected_cost": "Expected cost",
    "referral_rate": "Referral rate",
    "balanced_accuracy": "Balanced accuracy",
    "accuracy": "Accuracy",
    "high_risk_precision": "High-risk precision",
    "macro_f1": "Macro F1",
    "kappa_quadratic": "Quadratic kappa",
}


def _md(frame: pd.DataFrame, index: bool = True) -> str:
    try:
        return frame.to_markdown(index=index)
    except ImportError:
        return "```\n" + frame.to_string(index=index) + "\n```"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--artifacts", default=None)
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    art = Path(args.artifacts) if args.artifacts else C.ARTIFACTS_DIR
    out = Path(args.out) if args.out else C.PAPER_DIR / "generated_tables.md"

    meta_path = art / "run_metadata.json"
    if not meta_path.exists():
        print(f"No run metadata in {art}. Run: python scripts/train.py")
        return 1
    meta = json.loads(meta_path.read_text())

    parts: list[str] = []
    warning = ("> **SYNTHETIC DATA.** Every number below is a pipeline "
               "demonstration with no clinical meaning.\n"
               if meta["data_is_synthetic"] else "")

    parts.append(
        f"# Generated tables\n\n{warning}\n"
        f"Auto-generated by `scripts/make_paper_tables.py` — do not edit by hand.\n\n"
        f"| Run property | Value |\n|---|---|\n"
        f"| Generated | {meta['generated_utc']} |\n"
        f"| Data source | `{meta['data_source']}` |\n"
        f"| Rows (raw / clean) | {meta['data_rows_raw']} / {meta['data_rows_clean']} |\n"
        f"| Data SHA-256 | `{meta['data_sha256'][:16]}...` |\n"
        f"| Cross-validation | {meta['cv']['folds']} folds x {meta['cv']['repeats']} repeats, seed {meta['cv']['seed']} |\n"
        f"| Glucose interpretation | `{meta['bs_interpretation']}` |\n"
        f"| Referral budget | {meta['max_referral_rate']:.0%} |\n"
        f"| Selected model | `{meta['selected_model']}` |\n"
        f"| Operating point | t_high={meta['final_operating_point']['t_high']:.2f}, "
        f"t_escalate={meta['final_operating_point']['t_escalate']:.2f} |\n"
        f"| Attribution | {meta['attribution_method']} |\n"
    )

    # Table 1 -- main results
    results = pd.read_csv(art / "results_table.csv", index_col=0)
    cols = [c for c in HEADLINE if c in results.columns]
    parts.append("\n## Table 1. Cross-validated performance (mean ± std)\n\n"
                 + _md(results[cols].rename(columns=PRETTY)))

    # Table 2 -- matched referral load
    matched = pd.read_csv(art / "matched_referral_comparison.csv")
    parts.append("\n## Table 2. Every model at the guideline baseline's referral load\n\n"
                 + _md(matched.rename(columns=PRETTY), index=False))

    # Table 3 -- guideline calibration
    conf = pd.read_csv(art / "calibration_confusion.csv", index_col=0)
    parts.append("\n## Table 3. Dataset labels vs. published thresholds\n\n" + _md(conf))

    # Table 4 -- glucose sensitivity
    bs = pd.read_csv(art / "bs_interpretation_sensitivity.csv")
    parts.append("\n## Table 4. Sensitivity to the undocumented glucose column\n\n"
                 + _md(bs, index=False))

    # Table 5 -- rule activity
    act = pd.read_csv(art / "guideline_rule_activity.csv", index_col=0)
    parts.append("\n## Table 5. Guideline criterion firing rates (%)\n\n" + _md(act))

    # Table 6 -- attribution
    imp = pd.read_csv(art / "feature_importance.csv", index_col=0)
    parts.append(f"\n## Table 6. Feature attribution ({meta['attribution_method']})\n\n"
                 + _md(imp.round(4)))

    # Table 7 -- threshold stability
    pts = pd.read_csv(art / "operating_points.csv")
    tuned = pts[~pts["model"].str.endswith("_baseline")]
    if not tuned.empty:
        stab = (tuned.groupby("model")["t_high"]
                .agg(["mean", "std", "min", "max"]).round(3))
        parts.append("\n## Table 7. Stability of the tuned referral threshold\n\n"
                     + _md(stab))

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
